# PROXY: Your server accepts connection from trusted ENTRIES or from clients.
#      * If you are a bungeecord PROXY, do NOT expose your port to public network.
#      * If you are a bungeecord PROXY, please disable online mode.
#      * Only Velocity PROXIES support RSA/KEY verification and direct client connection.
role = "PROXY"
# Set to true to enable debug output
verbose = false

# Contents below are valid for PROXY servers
[proxy]
    # Set to true to enable clients directly connecting to the server.
    allow-client-connection = false
    # Set to
    send-switch-server-plugin-message-to-entry = true

    [proxy.skin-service-backend]
        # Both empty: Disabled
        # Both not empty: Will work only in whitelist mode
        # Note: If enabled, the plugin will also check the skin server of directly connected players.
        blocked = []
        allowed = []
        union-query-api = "https://skin.mualliance.ltd/api/union/profile/mapped/byuuid/"