# PROXY: Your server accepts connection from trusted ENTRIES or from clients.
role = "PROXY"
# Set to true to enable debug output
verbose = false

# Contents below are valid for PROXY servers
[proxy]
# Set to false to disable connection from clients.
    allow-client-connection = false

    [proxy.skin-service-backend]
        # Both empty: Disabled
        # Both not empty: Will work only in whitelist mode
        blocked = []
        allowed = []
        union-query-api = "https://skin.mualliance.ltd/api/union/profile/mapped/byuuid/"